version: '3'
services:
  app:
    image: phylogenyexplorer/explorer
    environment:
      - MONGO_URL=mongo
      - PHYLEX_PUBLIC_API_HOSTNAME=demo.phylogenyexplorerproject.com:5500
      - PHYLEX_ADMIN_API_HOSTNAME=demo.phylogenyexplorerproject.com:5000
      - PHYLEX_WEBSITE_HOSTNAME=demo.phylogenyexplorerproject.com:3000
    ports:
      - "3000:3000"
      - "5000:5000"
      - "5500:5500"
    depends_on:
      - mongoseed
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongoseed:
    image: phylogenyexplorer/mongoseed
    depends_on:
      - mongo

  nginx:
    image: phylogenyexplorer/nginx-demo:0.2
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - app
    links:
      - app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

