version: '3'
services:
  app:
    image: phylogenyexplorer/explorer
    environment:
      - MONGO_URL=mongo
    ports:
      - "3000:3000"
      - "5000:5000"
      - "5500:5500"
    depends_on:
      - mongoseed
    volumes:
      - certbot-webroot-evsoul:/app/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongoseed:
    image: phylogenyexplorer/mongoseed
    depends_on:
      - mongo

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - URL=demo.phylogenyexplorerproject.com
      - SUBDOMAINS=www,
      - VALIDATION=http
      - EMAIL=it@phylogenyexplorerproject.com
    volumes:
      - certbot-webroot-evsoul:/webroots/demo.phylogenyexplorerproject.com/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  nginx:
    image: phylogenyexplorer/nginx-demo:0.2
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - letsencrypt
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-webroot-evsoul:/webroots/demo.phylogenyexplorerproject.com/.well-known
      - certbot-letsencrypt:/etc/letsencrypt
    # command: [nginx-debug, '-g', 'daemon off;']

volumes:
  certbot-webroot-evsoul:
  certbot-letsencrypt:
